name: Golang Linting

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  golang-checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.24]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: |
          go mod download
      - name: Tidy dependencies
        run: |
          go mod tidy -diff
      - name: Check Format
        run: |
          gofmt -s -l database logging sse *.go
